# Generated by Django 5.1.7 on 2025-03-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_question_answer_delete_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='Проблема'),
            preserve_default=False,
        ),
    ]
